"""initial_schema

Revision ID: e2746ef4e845
Revises: 
Create Date: 2025-12-31 17:45:46.957216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2746ef4e845'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_types',
    sa.Column('content_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('content_type_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parameters',
    sa.Column('parameter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('parameter_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('plans',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('source_types',
    sa.Column('source_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('source_type_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('generation_limits',
    sa.Column('tier', sa.Text(), nullable=False),
    sa.Column('max_generations', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tier')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parameter_values',
    sa.Column('value_id', sa.UUID(), nullable=False),
    sa.Column('parameter_id', sa.UUID(), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameters.parameter_id'], ),
    sa.PrimaryKeyConstraint('value_id')
    )
    op.create_table('quota_usage',
    sa.Column('usage_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('quota_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_table('quotas',
    sa.Column('quota_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('quota_type', sa.String(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('quota_id')
    )
    op.create_table('rate_limits',
    sa.Column('rate_limit_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('rate_limit_id')
    )
    op.create_table('sources',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_identifier', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('source_type_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['source_type_id'], ['source_types.source_type_id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_table('templates',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.Text(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('template_image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('user_activity',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.Text(), nullable=False),
    sa.Column('activity_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('user_generations',
    sa.Column('user_thread_generation_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('generations_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('user_thread_generation_id')
    )
    op.create_table('content',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('content_type_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('thread_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['content_type_id'], ['content_types.content_type_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.template_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('media',
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=False),
    sa.Column('media_type', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('media_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.subscription_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('source_metadata',
    sa.Column('metadata_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('metadata_id')
    )
    op.create_table('template_parameters',
    sa.Column('template_param_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('parameter_id', sa.UUID(), nullable=True),
    sa.Column('value_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameters.parameter_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.template_id'], ),
    sa.ForeignKeyConstraint(['value_id'], ['parameter_values.value_id'], ),
    sa.PrimaryKeyConstraint('template_param_id')
    )
    op.create_table('url_references',
    sa.Column('url_reference_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('file_category', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('url_reference_id')
    )
    op.create_table('user_selected_sources',
    sa.Column('selection_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('selection_id')
    )
    op.create_table('content_analytics',
    sa.Column('analytics_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('analytics_id')
    )
    op.create_table('content_sources',
    sa.Column('content_source_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('content_source_id')
    )
    op.create_table('content_tags',
    sa.Column('content_tag_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('tag_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.PrimaryKeyConstraint('content_tag_id')
    )
    # Create LangGraph checkpoint tables with correct schema
    # Note: blob column MUST be bytea (LargeBinary), not text
    op.create_table(
        'checkpoints',
        sa.Column('thread_id', sa.Text(), nullable=False),
        sa.Column('checkpoint_ns', sa.Text(), nullable=False, server_default=''),
        sa.Column('checkpoint_id', sa.Text(), nullable=False),
        sa.Column('parent_checkpoint_id', sa.Text(), nullable=True),
        sa.Column('type', sa.Text(), nullable=True),
        sa.Column('checkpoint', postgresql.JSONB(), nullable=False),
        sa.Column('metadata', postgresql.JSONB(), nullable=False, server_default='{}'),
        sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id')
    )
    op.create_index('checkpoints_thread_id_idx', 'checkpoints', ['thread_id'])

    op.create_table(
        'checkpoint_blobs',
        sa.Column('thread_id', sa.Text(), nullable=False),
        sa.Column('checkpoint_ns', sa.Text(), nullable=False, server_default=''),
        sa.Column('channel', sa.Text(), nullable=False),
        sa.Column('version', sa.Text(), nullable=False),
        sa.Column('type', sa.Text(), nullable=False),
        sa.Column('blob', sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version')
    )
    op.create_index('checkpoint_blobs_thread_id_idx', 'checkpoint_blobs', ['thread_id'])

    op.create_table(
        'checkpoint_writes',
        sa.Column('thread_id', sa.Text(), nullable=False),
        sa.Column('checkpoint_ns', sa.Text(), nullable=False, server_default=''),
        sa.Column('checkpoint_id', sa.Text(), nullable=False),
        sa.Column('task_id', sa.Text(), nullable=False),
        sa.Column('idx', sa.Integer(), nullable=False),
        sa.Column('channel', sa.Text(), nullable=False),
        sa.Column('type', sa.Text(), nullable=True),
        sa.Column('blob', sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx')
    )
    op.create_index('checkpoint_writes_thread_id_idx', 'checkpoint_writes', ['thread_id'])

    op.create_table(
        'checkpoint_migrations',
        sa.Column('v', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('v')
    )
    op.alter_column('profiles', 'role',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profiles', 'subscription_status',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profiles', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profiles', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profiles', 'generations_used',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_profiles_is_deleted'), table_name='profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_profiles_is_deleted'), 'profiles', ['is_deleted'], unique=False)
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('profiles', 'generations_used',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('profiles', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('profiles', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text('\'{"theme": "light", "defaultView": "blog", "emailNotifications": true}\'::jsonb'),
               existing_nullable=True)
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('profiles', 'subscription_status',
               existing_type=sa.TEXT(),
               server_default=sa.text("'none'::text"),
               existing_nullable=True)
    op.alter_column('profiles', 'role',
               existing_type=sa.TEXT(),
               server_default=sa.text("'free'::text"),
               existing_nullable=True)
    # Drop checkpoint tables
    op.drop_index('checkpoint_writes_thread_id_idx', table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_index('checkpoint_blobs_thread_id_idx', table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_index('checkpoints_thread_id_idx', table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_table('checkpoint_migrations')
    op.drop_table('content_tags')
    op.drop_table('content_sources')
    op.drop_table('content_analytics')
    op.drop_table('user_selected_sources')
    op.drop_table('url_references')
    op.drop_table('template_parameters')
    op.drop_table('source_metadata')
    op.drop_table('payments')
    op.drop_table('media')
    op.drop_table('content')
    op.drop_table('user_generations')
    op.drop_table('user_activity')
    op.drop_table('templates')
    op.drop_table('subscriptions')
    op.drop_table('sources')
    op.drop_table('rate_limits')
    op.drop_table('quotas')
    op.drop_table('quota_usage')
    op.drop_table('parameter_values')
    op.drop_table('tags')
    op.drop_table('generation_limits')
    op.drop_table('source_types')
    op.drop_table('plans')
    op.drop_table('parameters')
    op.drop_table('content_types')
    # ### end Alembic commands ###
